In [2]:
import pandas as pd

In [3]:
film_dataset = pd.read_csv("original/TMDB_movie_dataset_v11.csv")

Preliminary overview - This is a large dataset, with 1402844 rows and 24 columns. It contains 1 million + movies. I can see that the column headers already follow a snake_case naming convention, meaning I don't have to worry about implementing it.

Below are the column names, their data types and my additional notes on them:

* id (*dtype: integer*) - a unique identification key for each movie. **Keep this column**, as it could come in handy if I use another movie dataset.

* title (*dtype: object*) - 18 missing values - each movie's title. **Keep this column**.

* vote_average(*dtype: float*) - the average user rating, taken from the TMDB movie database. Could be interesting to do something with the general user popularity in my analysis. However, these particular average scores are from one site only and would not represent true general viewer ratings, in my opinion. If I could combine the data from this column with that of other datasets', which include user ratings from sites like IMDB and Rotten Tomatos, I could use it for my analysis. The issue is that right now, I'm exploring whether space missions affect the number of Sci-Fi movies that are made, **their popularity (in terms of people going to see the movie - box office metrics)**. Whether the film is any good or is enjoyed by the general audience is not a concern (**although audience reception could affect box office raitings, which would impact my analysis - I need the viewers' opinions during the first 1-2 weeks of release, as that would be the truest metric I could use**). **Delete this column and try to find more targeted formation**.


* vote_count (*dtype: integer*) - total count of viewer votes received. Informs the vote_average ratings. **Delete this column**.

* status (*dtype: object*) - the status of the movie (released, in production, etc.). **Investigate this and realease_date further**.

* release_date (*dtype: object*) - 306881 missing values - should be the release date of the movie. I say should, because **I've noticed a mismatch between the status and release_date columns**. Rumoured movies have release dates; some movies in post and pre - production don't have release dates. **Investigate further**

* revenue (*dtype: integer*) - revenue generated, **however it doesn't specify the currency and there are a lot of movies where the revenue is 0**. **Delete**; the overall revenue of a movie is not connected to my project.

* runtime (*dtype: integer*) - duration of the movie in minutes. **Don't need it for my analysis - delete**.

* adult (*dtype: bool*) - column has False if the movie is not suitable for children and True if it is. The logic here is a bit backwords in my opinion. **Don't need it for my analysis - delete**.

* backdrop_path (*dtype: object*) - 1052902 missing values - url for the movie backdrop photo. **Don't need it for my analysis - delete**.

* budget (*dtype: integer*) - shows the budget allocated for the movie. The column has no inforamtion however, about the currency these budgets are in. **Don't need it for my analysis - delete**.

* homepage (*dtype: object*) - 1258298 missing values - contains the URL for the movie's official website, for marketing purposes. **Don't need it for my analysis - delete**.

* imdb_id (*dtype: object*) - 737938 missing values - tells us what the film's ID is in IMDB's dataset. **Keep it in case I want to combine this data with another dataset**, maybe it could help.

* original_language (*dtype: object*) - the original language spoken in the film. **Try to consolidate this, original_title and production_countries into one single column - origin_country** (so that I can group the films by the countries that made them; would be interesting to poke around and see if I find something interesting, when I group this data with the space missions one).

* original_title (*dtype: object*) - 18 missing values - the original title of the film (in it's native language). **Consolidate into origin_country**.

* overview (*dtype: object*) - 320603 missing values - gives an overview of the movie's plot. **Keep this column**.

* popularity (*dtype: float*) - popularity score of the movie. There is no information howver on how that score is calculated; what is taken into account here or not; how it differs from the vote_average column. **Too many unknows to use it efficiently - delete.**

* poster_path (*dtype: object*) - 495110 missing values - url for the movie poster photo. **Don't need it for my analysis - delete**.

* tagline (*dtype: object*) - 1207469 missing values - the movie's marketing tagline. **Keep this column** - maybe I can use it in tandem with the overview and keywords columns.

* genres (*dtype: object*) - 613360 missing values - the genre or genres of the movie. **Keep this column**.

* production_companies (*dtype: object*) - 803373 missing values - the production house/ houses that made the movie. **Keep this column** - could open new/ interesting analysis possibilities (e.g. which production company had made or currently makes the most sci-fi movies and is there a correlation with the space mission's timeframes).

* production_countries (*dtype: object*) - 675619 missing values - countries that took part in the film's making (on-set or location shooting, pre and post production) **Consolidate into origin_country**.

* spoken_languages (*dtype: object*) - 648632 missing values - what language's are spoken in the movie. **Don't need it for my analysis - delete**.

* keywords (*dtype: object*) - 1054288 missing values -keywords, associated with the movie. No information of where they are taken from and the criteria of choosing them. Could be misleading. **Keep this column**.

Duplicate titles issue - there are 77641 duplicates in the title column, 2203 duplicates in the imdb column and 883 duplicates in the id field. I started cleaning the duplicates by subseting the three columns and removing rows where the data was identical. I then did the same, but I subsetted the three columns into groups of two, changing the combinations (title, id, imdb_id; then title and id; then id and imdb_id and so on). I managed to reduce the title column duplicates to 39852 and I was able to clean the id and imdb_id columns entirely. The id column was the first to be cleared of duplicates. The imdb_id column still had some instances of duplicate values however. I examined the rows where there were duplicates and found out that the duplicate imdb_id values were for different regional releases of a movie. So a movie released in the US (english), France (french), Spain (spanish) and so on would have a different id, but the same imbd_id. Another observation I made is that for some movies, a different release date in each country warrants a separate entry and id in the dataset (The imbd_id remained the same however). There were also some movies that were just duplicated due to a difference in spelling (be it by mistake or on purpose) or a differnce in the row information. I tried to consolidate the information, across the duplicate rows, as much as possible in Excel and then I removed the duplicates from the dataset. Only title duplicates remained with the majority being words or small sentences like 'Home', 'Mother', 'The Return', etc. After checking the titles I was able to find only one real duplicate which was 'Black Panther: Wakanda Forever' and I removed it.

For the status/ release_date columns - I first deleted all movie records before 1960, as they aren't a part of my analysis scope. I also removed rows where there's an NA value in the release_date and genres columns. I then checked the rows where the status is anything, except for 'Released. There were around 14 000 entries where the status was different from released and for almost all of them, there was a mismatch between their status and release_date (films are in production, rumored or in post-production, but have a release date < 2026). These mimatched entries start from row 358326, meaning that there are still thousands of correct film entries. A large part of these problematic films are foreign (outside of the US). I cannot check whether each of the planned or in production movies actually got released or not. 
I have deleted all of the 'Rumored' and 'Planned' entries, eliminating the biggest uncertainty factor from the dataset and allowing the data to be as certain as possible. This way I can more clearly test my hypothesis, without venturing into the realm of making predictions or relying on speculated trends. There were also some films with a "Canceled" status. which I also deleted. In the end I also decided to delete the 'In production' entries and the 'Post Production' ones. My reasoning for this is - a film can begin production, but end up in production hell where it is never finished - either due to money running out, not enough man power or other countless problems arising. The same can happen in post production. Seeing as I don't want to speculate or make any future predictions, I stuck only with the released movies.

For the production_countries column - changed United States of America to US and United Kingdom to UK, so it's the same as the space missions dataset.

In [4]:
film_dataset.head(5)
#film_dataset.tail(5)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,8.417,32571,Released,2014-11-05,701729206,169,False,/pbrkL804c8yAv3zBZR4QPEafpAR.jpg,...,Interstellar,The adventures of a group of explorers who mak...,140.241,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","United Kingdom, United States of America",English,"rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,8.512,30619,Released,2008-07-16,1004558444,152,False,/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg,...,The Dark Knight,Batman raises the stakes in his war on crime. ...,130.643,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","United Kingdom, United States of America","English, Mandarin","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,7.573,29815,Released,2009-12-15,2923706026,162,False,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,...,Avatar,"In the 22nd century, a paraplegic Marine is di...",79.932,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","United States of America, United Kingdom","English, Spanish","future, society, culture clash, space travel, ..."
4,24428,The Avengers,7.710,29166,Released,2012-04-25,1518815515,143,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,...,The Avengers,When an unexpected enemy emerges and threatens...,98.082,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,United States of America,"English, Hindi, Russian","new york city, superhero, shield, based on com..."

In [6]:
#Preliminary overview of the dataset
print(f"Rows x columns dimensions: {film_dataset.shape}")
print(f"Column names: {film_dataset.columns}")
print(f"Each columns data type: {film_dataset.dtypes}")
print(f"Missing values per column: {film_dataset.isna().sum()}")

Final rows x columns dimensions: (1402844, 24)
Final column names: Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')
Each columns data type: id                        int64
title                    object
vote_average            float64
vote_count                int64
status                   object
release_date             object
revenue                   int64
runtime                   int64
adult                      bool
backdrop_path            object
budget                    int64
homepage                 object
imdb_id                  object
original_language        object
original_title           object
overview                 object
popularity              float64
poster_path              object
tagline                  object
genres                   object
production_companies     object
production_countries     object
spoken_languages         object
keywords                 object
dtype: object
Missing values per column: id                            0
title                        18
vote_average                  0
vote_count                    0
status                        0
release_date             306881
revenue                       0
runtime                       0
adult                         0
backdrop_path           1052902
budget                        0
homepage                1258298
imdb_id                  737938
original_language             0
original_title               18
overview                 320603
popularity                    0
poster_path              495110
tagline                 1207469
genres                   613360
production_companies     803373
production_countries     675619
spoken_languages         648632
keywords                1054288
dtype: int64

In [140]:
#Cleaning the dataset. 
#Removing the uneeded columns.
film_dataset_adjusted = film_dataset.drop(columns = ["vote_average", "vote_count", "revenue", "runtime", "adult", "backdrop_path", "budget", "homepage", "popularity", "poster_path", "spoken_languages"])

#Change the values in the release_date column from objects to real dates.
film_dataset_adjusted['release_date'] = pd.to_datetime(film_dataset_adjusted['release_date'], errors='coerce')

#Delete rows with release_date before 1st January 1960.
film_dataset_adjusted = film_dataset_adjusted[film_dataset_adjusted['release_date'] >= '1960-01-01']

#Remove the rows which have an NA value in the release_date column.
film_dataset_adjusted = film_dataset_adjusted.dropna(subset=['release_date'])

film_dataset_adjusted = film_dataset_adjusted.dropna(subset=['genres'])

#Process of cleaning duplicate movies.
#Remove rows where there are duplicate title, imdb and id values (only combinations of all three), while keeping the firs instance of that combination. 
film_dataset_adjusted.drop_duplicates(
    subset=['title', 'imdb_id', 'id'],
    keep='first',
    inplace=True)

#Remove rows where there are duplicate title and imdb values (only combinations of those two), while keeping the firs instance of that combination.
film_dataset_adjusted.drop_duplicates(
    subset=['title', 'imdb_id'],
    keep='first',
    inplace=True)

#Remove rows where there are duplicate title and id values (only combinations of those two), while keeping the firs instance of that combination.
film_dataset_adjusted.drop_duplicates(
    subset=['title', 'id'],
    keep='first',
    inplace=True)

#Remove the remaining duplicate movie, by referencing its row
film_dataset_adjusted = film_dataset_adjusted.drop(799201)

#Remove rows where there are duplicate imdb_id values, while keeping the firs instance they appear in.
film_dataset_adjusted.drop_duplicates(
    subset=['imdb_id'],
    keep='first',
    inplace=True)

#Remove the rows where the status is either "Rumored" or 'Planned" in order to manage uncertainty in the dataset
film_dataset_adjusted = film_dataset_adjusted[~film_dataset_adjusted["status"].isin(["Rumored", "Planned", "Canceled", "In Production", "Post Production"])]

#Changes the country names for the US and the UK
film_dataset_adjusted["production_countries"] = (film_dataset_adjusted["production_countries"].str.replace("United Kingdom", "UK", regex=False).str.replace("United States of America", "USA", regex=False))

In [127]:
#Check the adjusted dataset for duplicates across title, id and imdb_id (each line of code needs to be executed in a separate cell)
film_dataset_adjusted["imdb_id"].value_counts()[lambda x: x > 1]
film_dataset_adjusted["title"].value_counts()[lambda x: x > 1]
film_dataset_adjusted["id"].value_counts()[lambda x: x > 1]

Series([], Name: count, dtype: int64)

In [142]:
#Exported the modified version so I can have a look at the dataset so far in its entirety
film_dataset_adjusted.to_csv("film_dataset_adjusted.csv", index=False)
film_dataset_adjusted

,id,title,status,release_date,imdb_id,original_language,original_title,overview,tagline,genres,production_companies,production_countries,keywords
0,27205,Inception,Released,2010-07-15,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate es...",Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","UK, USA","rescue, mission, dream, airplane, paris, franc..."
1,157336,Interstellar,Released,2014-11-05,tt0816692,en,Interstellar,The adventures of a group of explorers who mak...,Mankind was born on Earth. It was never meant ...,"Adventure, Drama, Science Fiction","Legendary Pictures, Syncopy, Lynda Obst Produc...","UK, USA","rescue, future, spacecraft, race against time,..."
2,155,The Dark Knight,Released,2008-07-16,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,Welcome to a world without rules.,"Drama, Action, Crime, Thriller","DC Comics, Legendary Pictures, Syncopy, Isobel...","UK, USA","joker, sadism, chaos, secret identity, crime f..."
3,19995,Avatar,Released,2009-12-15,tt0499549,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",Enter the world of Pandora.,"Action, Adventure, Fantasy, Science Fiction","Dune Entertainment, Lightstorm Entertainment, ...","USA, UK","future, society, culture clash, space travel, ..."
4,24428,The Avengers,Released,2012-04-25,tt0848228,en,The Avengers,When an unexpected enemy emerges and threatens...,Some assembly required.,"Science Fiction, Action, Adventure",Marvel Studios,USA,"new york city, superhero, shield, based on com..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1402821,861986,The Secret Force,Released,1995-12-12,tt0371186,en,The Secret Force,Three Vietnam vets are targeted by the governm...,NaN,Action,NaN,South Africa,NaN
1402822,861987,War & Honey,Released,2021-02-16,tt16024742,en,War & Honey,Soldiers returning from the frontlines in east...,NaN,Documentary,NaN,"Ukraine, USA",NaN
1402831,862000,Beach Boy,Released,2021-09-03,tt11730242,en,Beach Boy,"Ben-David chases after his elusive first kiss,...",NaN,"Drama, Comedy",Red Digital Cinema,USA,"coming of age, crush, first kiss, short film"
1402835,862004,A Young Crane's Long Journey,Released,2021-08-21,tt16528888,fi,Kurjenpojan pitkä matka,Jouni Hiltunen has filmed Cranes for many year...,NaN,Documentary,NaN,Finland,NaN
1402838,862007,Pimeys odottaa,Released,1985-03-08,tt0141730,fi,Pimeys odottaa,Matti Mäki is a young man who gets involved wi...,NaN,"Crime, Thriller",Villealfa Filmproductions,Finland,film noir

In [143]:
#Final overview of the modified dataset
print(f"Rows x columns dimensions: {film_dataset_adjusted.shape}")
print(f"Column names: {film_dataset_adjusted.columns}")
print(f"Each columns data type: {film_dataset_adjusted.dtypes}")
print(f"Missing values per column: {film_dataset_adjusted.isna().sum()}")

Rows x columns dimensions: (388688, 13)
Column names: Index(['id', 'title', 'status', 'release_date', 'imdb_id', 'original_language',
       'original_title', 'overview', 'tagline', 'genres',
       'production_companies', 'production_countries', 'keywords'],
      dtype='object')
Each columns data type: id                               int64
title                           object
status                          object
release_date            datetime64[ns]
imdb_id                         object
original_language               object
original_title                  object
overview                        object
tagline                         object
genres                          object
production_companies            object
production_countries            object
keywords                        object
dtype: object
Missing values per column: id                           0
title                        0
status                       0
release_date                 0
imdb_id                      1
original_language            0
original_title               0
overview                 42566
tagline                 307116
genres                       0
production_companies    140043
production_countries     77631
keywords                228363
dtype: int64

In [147]:
#Exporting the final dataset
film_dataset_adjusted.to_csv("movies_dataset.csv", index=False)